FROM openjdk:17-alpine
MAINTAINER  Stanislav Gavrilov <stall.93@yandex.ru>
COPY target/parsemsg-0.0.1-SNAPSHOT.jar /home/parsemsg-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","/home/parsemsg-0.0.1-SNAPSHOT.jar"]
